// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StartTestApi.Data;

#nullable disable

namespace StartTestApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260121084910_adddata")]
    partial class adddata
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StartTestApi.Data.Entities.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Beschrijving")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EindDatumTijd")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsGeannuleerd")
                        .HasColumnType("bit");

                    b.Property<DateTime>("StartDatumTijd")
                        .HasColumnType("datetime2");

                    b.Property<string>("Titel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Beschrijving = "Leer grenzen aangeven en zelfzeker communiceren.",
                            EindDatumTijd = new DateTime(2026, 3, 10, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            IsGeannuleerd = false,
                            StartDatumTijd = new DateTime(2026, 3, 10, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            Titel = "Assertiviteitstraining voor beginners"
                        },
                        new
                        {
                            Id = 2,
                            Beschrijving = "Rustige yogasessie om de dag af te sluiten.",
                            EindDatumTijd = new DateTime(2026, 3, 12, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            IsGeannuleerd = false,
                            StartDatumTijd = new DateTime(2026, 3, 12, 19, 30, 0, 0, DateTimeKind.Unspecified),
                            Titel = "Avond-Yoga voor ontspanning"
                        });
                });

            modelBuilder.Entity("StartTestApi.Data.Entities.Inschrijving", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DeelnemerEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeelnemerNaam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<DateTime>("InschrijfDatumTijd")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.ToTable("Inschrijvingen");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DeelnemerEmail = "jan@jansen.com",
                            DeelnemerNaam = "Jan Jansen",
                            EventId = 1,
                            InschrijfDatumTijd = new DateTime(2026, 2, 20, 14, 15, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            DeelnemerEmail = "piet@gmail.com",
                            DeelnemerNaam = "Piet Pietersen",
                            EventId = 1,
                            InschrijfDatumTijd = new DateTime(2026, 2, 22, 10, 30, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("StartTestApi.Data.Entities.Inschrijving", b =>
                {
                    b.HasOne("StartTestApi.Data.Entities.Event", "Event")
                        .WithMany("Inschrijvingen")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("StartTestApi.Data.Entities.Event", b =>
                {
                    b.Navigation("Inschrijvingen");
                });
#pragma warning restore 612, 618
        }
    }
}
