// <auto-generated />
using System;
using AfsprakenbeheerPsycholoog.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AfsprakenbeheerPsycholoog.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260626102817_AddReminderSentProperty")]
    partial class AddReminderSentProperty
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.23");

            modelBuilder.Entity("AfsprakenbeheerPsycholoog.Authentication.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Achternaam")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PatientId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("Voornaam")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.HasIndex("PatientId");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("AfsprakenbeheerPsycholoog.Data.Entities.Afspraak", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Eindtijd")
                        .HasColumnType("TEXT");

                    b.Property<string>("GoogleEventId")
                        .HasColumnType("TEXT");

                    b.Property<bool>("HerinneringVerzonden")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Opmerkingen")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PatientId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid?>("ReeksId")
                        .HasColumnType("TEXT");

                    b.Property<double?>("SentimentScore")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("Starttijd")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("TypeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GoogleEventId")
                        .IsUnique();

                    b.HasIndex("PatientId");

                    b.HasIndex("TypeId");

                    b.ToTable("Afspraken");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Eindtijd = new DateTime(2026, 4, 14, 11, 30, 0, 0, DateTimeKind.Unspecified),
                            HerinneringVerzonden = false,
                            PatientId = 1,
                            SentimentScore = 0.0,
                            Starttijd = new DateTime(2026, 4, 14, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Gepland",
                            TypeId = 1
                        },
                        new
                        {
                            Id = 2,
                            Eindtijd = new DateTime(2026, 4, 15, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            HerinneringVerzonden = false,
                            PatientId = 2,
                            SentimentScore = 0.0,
                            Starttijd = new DateTime(2026, 4, 15, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Gepland",
                            TypeId = 2
                        },
                        new
                        {
                            Id = 3,
                            Eindtijd = new DateTime(2026, 4, 1, 9, 45, 0, 0, DateTimeKind.Unspecified),
                            HerinneringVerzonden = false,
                            PatientId = 1,
                            SentimentScore = 0.45000000000000001,
                            Starttijd = new DateTime(2026, 4, 1, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Voltooid",
                            TypeId = 3
                        },
                        new
                        {
                            Id = 4,
                            Eindtijd = new DateTime(2026, 3, 20, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            HerinneringVerzonden = false,
                            Opmerkingen = "Patiënt heeft afgezegd",
                            PatientId = 3,
                            SentimentScore = -0.29999999999999999,
                            Starttijd = new DateTime(2026, 3, 20, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = "Geannuleerd",
                            TypeId = 2
                        });
                });

            modelBuilder.Entity("AfsprakenbeheerPsycholoog.Data.Entities.AfspraakType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Kleurcode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("StandaardDuurMinuten")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("VereistPatient")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("AfspraakTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Kleurcode = "#4A90D9",
                            Naam = "Intake",
                            StandaardDuurMinuten = 90,
                            VereistPatient = true
                        },
                        new
                        {
                            Id = 2,
                            Kleurcode = "#7ED321",
                            Naam = "Therapie",
                            StandaardDuurMinuten = 60,
                            VereistPatient = true
                        },
                        new
                        {
                            Id = 3,
                            Kleurcode = "#F5A623",
                            Naam = "Evaluatie",
                            StandaardDuurMinuten = 45,
                            VereistPatient = true
                        },
                        new
                        {
                            Id = 4,
                            Kleurcode = "#D0021B",
                            Naam = "Crisis",
                            StandaardDuurMinuten = 30,
                            VereistPatient = true
                        });
                });

            modelBuilder.Entity("AfsprakenbeheerPsycholoog.Data.Entities.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Achternaam")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DossierNummer")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double?>("EmotioneleStabiliteit")
                        .HasColumnType("REAL");

                    b.Property<DateOnly>("Geboortedatum")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActief")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Telefoonnummer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("VerwijderdOp")
                        .HasColumnType("TEXT");

                    b.Property<string>("VerwijderdReden")
                        .HasColumnType("TEXT");

                    b.Property<string>("Voornaam")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Patienten");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Achternaam = "Janssens",
                            DossierNummer = "DOS-001",
                            Email = "jan@test.be",
                            EmotioneleStabiliteit = 6.2000000000000002,
                            Geboortedatum = new DateOnly(1985, 3, 12),
                            IsActief = true,
                            Telefoonnummer = "0471000001",
                            Voornaam = "Jan"
                        },
                        new
                        {
                            Id = 2,
                            Achternaam = "Peeters",
                            Email = "marie@test.be",
                            EmotioneleStabiliteit = 4.7999999999999998,
                            Geboortedatum = new DateOnly(1992, 7, 4),
                            IsActief = true,
                            Telefoonnummer = "0471000002",
                            Voornaam = "Marie"
                        },
                        new
                        {
                            Id = 3,
                            Achternaam = "De Smedt",
                            DossierNummer = "DOS-002",
                            Email = "pieter@test.be",
                            EmotioneleStabiliteit = 7.5,
                            Geboortedatum = new DateOnly(1978, 11, 20),
                            IsActief = true,
                            Telefoonnummer = "0471000003",
                            Voornaam = "Pieter"
                        });
                });

            modelBuilder.Entity("AfsprakenbeheerPsycholoog.Data.Entities.PraktijkInstelling", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BufferMinuten")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Dinsdag2Actief")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DinsdagActief")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DinsdagEinde")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DinsdagEinde2")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DinsdagStart")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DinsdagStart2")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Donderdag2Actief")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("DonderdagActief")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DonderdagEinde")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DonderdagEinde2")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DonderdagStart")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DonderdagStart2")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GoogleCalendarId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("LocatieGoogleMeet")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LocatiePraktijk")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LocatieTelefoon")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Maandag2Actief")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("MaandagActief")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MaandagEinde")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MaandagEinde2")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MaandagStart")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("MaandagStart2")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MaximaleToekomstDagen")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MinimaalVoorafUren")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SlotDuurMinuten")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Vrijdag2Actief")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("VrijdagActief")
                        .HasColumnType("INTEGER");

                    b.Property<string>("VrijdagEinde")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VrijdagEinde2")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VrijdagStart")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("VrijdagStart2")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Woensdag2Actief")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("WoensdagActief")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WoensdagEinde")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WoensdagEinde2")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WoensdagStart")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WoensdagStart2")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Zaterdag2Actief")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ZaterdagActief")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ZaterdagEinde")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ZaterdagEinde2")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ZaterdagStart")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ZaterdagStart2")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Zondag2Actief")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ZondagActief")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ZondagEinde")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ZondagEinde2")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ZondagStart")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ZondagStart2")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PraktijkInstellingen");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BufferMinuten = 15,
                            Dinsdag2Actief = true,
                            DinsdagActief = true,
                            DinsdagEinde = "12:00",
                            DinsdagEinde2 = "17:00",
                            DinsdagStart = "09:00",
                            DinsdagStart2 = "13:00",
                            Donderdag2Actief = true,
                            DonderdagActief = true,
                            DonderdagEinde = "12:00",
                            DonderdagEinde2 = "17:00",
                            DonderdagStart = "09:00",
                            DonderdagStart2 = "13:00",
                            GoogleCalendarId = "primary",
                            LocatieGoogleMeet = true,
                            LocatiePraktijk = true,
                            LocatieTelefoon = true,
                            Maandag2Actief = true,
                            MaandagActief = true,
                            MaandagEinde = "12:00",
                            MaandagEinde2 = "17:00",
                            MaandagStart = "09:00",
                            MaandagStart2 = "13:00",
                            MaximaleToekomstDagen = 30,
                            MinimaalVoorafUren = 12,
                            SlotDuurMinuten = 60,
                            Vrijdag2Actief = true,
                            VrijdagActief = true,
                            VrijdagEinde = "12:00",
                            VrijdagEinde2 = "17:00",
                            VrijdagStart = "09:00",
                            VrijdagStart2 = "13:00",
                            Woensdag2Actief = true,
                            WoensdagActief = true,
                            WoensdagEinde = "12:00",
                            WoensdagEinde2 = "17:00",
                            WoensdagStart = "09:00",
                            WoensdagStart2 = "13:00",
                            Zaterdag2Actief = false,
                            ZaterdagActief = false,
                            ZaterdagEinde = "12:00",
                            ZaterdagEinde2 = "17:00",
                            ZaterdagStart = "10:00",
                            ZaterdagStart2 = "13:00",
                            Zondag2Actief = false,
                            ZondagActief = false,
                            ZondagEinde = "12:00",
                            ZondagEinde2 = "17:00",
                            ZondagStart = "10:00",
                            ZondagStart2 = "13:00"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("AfsprakenbeheerPsycholoog.Authentication.ApplicationUser", b =>
                {
                    b.HasOne("AfsprakenbeheerPsycholoog.Data.Entities.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("AfsprakenbeheerPsycholoog.Data.Entities.Afspraak", b =>
                {
                    b.HasOne("AfsprakenbeheerPsycholoog.Data.Entities.Patient", "Patient")
                        .WithMany("Afspraken")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("AfsprakenbeheerPsycholoog.Data.Entities.AfspraakType", "Type")
                        .WithMany("Afspraken")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Patient");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("AfsprakenbeheerPsycholoog.Authentication.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("AfsprakenbeheerPsycholoog.Authentication.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AfsprakenbeheerPsycholoog.Authentication.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("AfsprakenbeheerPsycholoog.Authentication.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AfsprakenbeheerPsycholoog.Data.Entities.AfspraakType", b =>
                {
                    b.Navigation("Afspraken");
                });

            modelBuilder.Entity("AfsprakenbeheerPsycholoog.Data.Entities.Patient", b =>
                {
                    b.Navigation("Afspraken");
                });
#pragma warning restore 612, 618
        }
    }
}
