// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShopAPI.Data;

#nullable disable

namespace ShopAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ShopAPI.Data.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "AI Glasses"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Food"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Drinks"
                        });
                });

            modelBuilder.Entity("ShopAPI.Data.Entities.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<int>("AmountStock")
                        .HasColumnType("int");

                    b.Property<decimal>("BuyPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TaxesLevelId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("TaxesLevelId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active = true,
                            AmountStock = 12,
                            BuyPrice = 589.99m,
                            CategoryId = 1,
                            Code = "X1",
                            Name = "XReal One Pro",
                            TaxesLevelId = 1
                        },
                        new
                        {
                            Id = 2,
                            Active = false,
                            AmountStock = 20,
                            BuyPrice = 399.99m,
                            CategoryId = 1,
                            Code = "XAir",
                            Name = "XReal Air Pro",
                            TaxesLevelId = 1
                        },
                        new
                        {
                            Id = 3,
                            Active = true,
                            AmountStock = 12,
                            BuyPrice = 1.00m,
                            CategoryId = 2,
                            Code = "FoodApple",
                            Name = "Apple",
                            TaxesLevelId = 2
                        },
                        new
                        {
                            Id = 4,
                            Active = true,
                            AmountStock = 12,
                            BuyPrice = 0.50m,
                            CategoryId = 3,
                            Code = "DrinkWWater",
                            Name = "Water",
                            TaxesLevelId = 3
                        });
                });

            modelBuilder.Entity("ShopAPI.Data.Entities.Tax", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TaxLevel")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Taxes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Standaard",
                            TaxLevel = 21
                        },
                        new
                        {
                            Id = 2,
                            Name = "Uitzonderingen en maaltijden",
                            TaxLevel = 12
                        },
                        new
                        {
                            Id = 3,
                            Name = "Basisnoden",
                            TaxLevel = 6
                        });
                });

            modelBuilder.Entity("ShopAPI.Data.Entities.Product", b =>
                {
                    b.HasOne("ShopAPI.Data.Entities.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("ShopAPI.Data.Entities.Tax", "TaxLevel")
                        .WithMany("Products")
                        .HasForeignKey("TaxesLevelId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("TaxLevel");
                });

            modelBuilder.Entity("ShopAPI.Data.Entities.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("ShopAPI.Data.Entities.Tax", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
